language: python
services:
  - redis-server
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip install -e .
script:
  - cram tests
  - python setup.py test
after_success:
  - coveralls
